### ISSUE TITLE
Invaild input may be blocked before jumping to other site

### ISSUE THREAD

**Issue by SodiumThiocyanate** [SnangOfficial/SnangOfficial.github.io#1]
When nothing is written in the input box, why not **give a warning** instead of directly jumping to the site?

**Comment by SnangOfficial** [comment]
> When nothing is written in the input box, why not **give a warning** instead of directly jumping to the site?

Good idea..
And don't burn night oil（别熬夜）, just for your health.

**Comment by SodiumThiocyanate** [comment]
@SnangOfficial Now [Luogu Online Judge](https://www.luogu.org) has roughly 4434 problems. May any non-integral input be blocked? When I fill the input box with number 0999, it directly jumps.

**Comment by SodiumThiocyanate** [comment]
@SnangOfficial extended_int must be finished before I prepare from my exams. Though value categories is complicated, I have to do this.
